apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: REPLACE_WITH_YOUR_REGISTRY/users-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: NOTIFICATION_SERVICE_URL
              value: "http://notification-service:8000/notify"
            - name: DATABASE_HOST
              value: "postgres-service"
            - name: DATABASE_NAME
              value: "proyecto_registro_usuarios"
            - name: DATABASE_USER
              value: "postgres"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: users-api-service
spec:
  selector:
    app: users-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
